use theforeman-rubocop gem
theforeman/foreman_plugin_template pull request #60
Opened 2024-03-19 19:43 UTC by archanaserver

2024-03-19 20:48 UTC, archanaserver commented
Gemspec/RequiredRubyVersion cop fix: https://github.com/theforeman/foreman_plugin_template/pull/61

2024-03-19 20:49 UTC, archanaserver commented
This needs CI config

2024-04-05 18:09 UTC, ekohl requested changes

2024-04-05 18:09 UTC, ekohl commented on Rakefile
> +rescue StandardError
You can be more specific
```suggestion
rescue LoadError
```

2024-04-05 18:09 UTC, ekohl commented on .rubocop.yml
>    Enabled: 111 # TODO: discuss and set this
I'd also drop this an the other 2. Just stick to `theforeman-rubocop` defaults. If we think it should be different, then that's the place to change it IMHO.

2024-04-05 18:09 UTC, ekohl commented on lib/tasks/foreman_plugin_template_tasks.rake
> +  task rubocop: :environment do
This whole task is no longer needed since we load RuboCop via the `Rakefile` instead.

2024-04-05 18:09 UTC, ekohl commented on rename.rb
> +  next if /\.git/.match?(path)
This is the same
```suggestion
  next if path.include?('.git')
```

But this should really use a different approach and that is to use `Find.prune` as noted in https://github.com/theforeman/foreman_plugin_template/pull/62#discussion_r1554074765

2024-04-05 18:09 UTC, ekohl commented on test/unit/foreman_plugin_template_test.rb
> +    User.current = User.find_by login: 'admin'
This doesn't look correct. Why does this need `:`?

2024-06-28 12:23 UTC, archanaserver commented
It is about the standardizing rubocop changes and to keep track of all the changes made in foreman_plugin_template:

- [x] https://github.com/theforeman/foreman_plugin_template/pull/61
- [ ] https://github.com/theforeman/foreman_plugin_template/pull/62

2024-12-05 11:20 UTC, ekohl approved these changes

2024-12-05 11:20 UTC, merged